name: Deploy to Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.TI_HUDSONCAROLINO_SSH_PRIVATE_KEY }}

      - name: Deploy app - QA Environment
        run: ssh -o StrictHostKeyChecking=no hudsoncarolino@162.240.52.227 '/deploy.sh/deploy.sh'
