name: Deploy to Server

on:
  push:
    branches:
      - main
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      LC_ALL: "en_US.UTF-8"
      LANG: "en_US.UTF-8"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.TI_HUDSONCAROLINO_SSH_PRIVATE_KEY }}

      - name: Deploy app - QA Environment
        run: ssh -o StrictHostKeyChecking=no -p 22022 hudsoncarolino@162.240.52.227 'sudo /home/hudsoncarolino/deploysite.sh'
